### ISSUE TITLE
Why convert to XML? Support for nested docs?

### ISSUE THREAD

**Issue by vruizext** [rsolr/rsolr#109]
If the documents are ruby hashes why convert it to XML, wouldn't be easier to convert to JSON?

Also, with this conversion is impossible to add nested documents. Using JSON, nested documents are added to "_childDocuments" field and Solr processes them automatically. With XML it's necessary to create a new doc and embed it into the parent.

**Comment by atz** [comment]
:+1:

**Comment by cbeer** [comment]
@vruizext RSolr 2.0.0.pre1 now uses JSON by default (with support for `_childDocuments_` and atomic updates). It's not quite as easy as `Hash#to_json`, but certainly better than building XML documents.
