### ISSUE TITLE
:fq not supported

### ISSUE THREAD

**Issue by dvohra** [rsolr/rsolr#113]
response = solr.get 'select', :params => {
:q=>'*:*',
:fq=>['field1', 'field2','field3']
}

The preceding query generates error:

ruby query.rb
query.rb:9: syntax error, unexpected tSYMBEG, expecting '}'
:fq=>['field1', 'field2','field3']

**Comment by jcoyne** [comment]
This code works for me:

```ruby
 response = solr.get 'select', :params => {
  :q=>':',
  :fq=>['field1', 'field2','field3']
}
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: {'responseHeader'=>{'status'=>400,'QTime'=>25,'params'=>{'q'=>':','fq'=>['field1','field2','field3'],'wt'=>'ruby'}},'error'=>{'msg'=>'no field name specified in query and no default specified via \'df\' param','code'=>400}}
```

**Comment by dvohra** [comment]
Still getting an error. 

Ruby script :require 'rubygems'
require 'rsolr'
solr = RSolr.connect :url=>'http://localhost:8983/solr/wlslog'

 response = solr.get 'select', :params => {
  :q=>'*:*',
 :fq=>['timestamp','code','msg']
}

Error:
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:284:in `
adapt_response': RSolr::Error::Http - 400 Bad Request (RSolr::Error::Http)
Error: {'responseHeader'=>{'status'=>400,'QTime'=>1,'params'=>{'q'=>'*:*','wt'=>
'ruby','fq'=>['timestamp','code','msg']}},'error'=>{'msg'=>'undefined field text
','code'=>400}}

URI: http://localhost:8983/solr/wlslog/select?wt=ruby&q=*%3A*&fq=timestamp&fq=co
de&fq=msg

Backtrace: C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.
rb:284:in `adapt_response'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:190:in `
execute'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:176:in `
send_and_receive'
(eval):2:in `get'
query4.rb:5:in `<main>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rsolr-1.0.13/lib/rsolr/clien
t.rb:190:in `execute'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rsolr-1.0.13/lib/rsolr/clien
t.rb:176:in `send_and_receive'
        from (eval):2:in `get'
        from query4.rb:5:in `<main>'
