### ISSUE TITLE
delete_by_id and delete_by_query do not delete

### ISSUE THREAD

**Issue by dvohra** [rsolr/rsolr#114]
The delete_by_id and delete_by_query methods do not delete.

Update:
The delete_by_id and delete_by_query do delete, but with a slight time lag.

**Comment by jcoyne** [comment]
Did you run a commit after doing the delete?  Solr doesn't push the changes to the queryable index until you commit.   Because the results show up after a delay, I suspect you have autoCommit with a time delay enabled in your solr configuration.

**Comment by dvohra** [comment]
Did not commit in ruby script but autocommit with delay is configured in solrconfig.xml. Thanks Justin.
