### ISSUE TITLE
fq not supported

### ISSUE THREAD

**Issue by dvohra** [rsolr/rsolr#115]
As the earlier issue has been closed, creating a new issue.
Still getting an error.

Ruby script :

require 'rubygems'
require 'rsolr'
solr = RSolr.connect :url=>'http://localhost:8983/solr/wlslog'

response = solr.get 'select', :params => {
:q=>'\*:\*',
:fq=>['timestamp','code','msg']
}

Error:
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:284:in `
adapt_response': RSolr::Error::Http - 400 Bad Request (RSolr::Error::Http)
Error: {'responseHeader'=>{'status'=>400,'QTime'=>1,'params'=>{'q'=>':','wt'=>
'ruby','fq'=>['timestamp','code','msg']}},'error'=>{'msg'=>'undefined field text
','code'=>400}}

URI: http://localhost:8983/solr/wlslog/select?wt=ruby&q=%3A&fq=timestamp&fq=co
de&fq=msg

Backtrace: C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.
rb:284:in adapt_response' C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:190:in
execute'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:176:in  send_and_receive' (eval):2:inget'
query4.rb:5:in <main>' from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rsolr-1.0.13/lib/rsolr/clien t.rb:190:inexecute'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rsolr-1.0.13/lib/rsolr/clien
t.rb:176:in send_and_receive' from (eval):2:inget'
from query4.rb:5:in `

**Comment by jcoyne** [comment]
That is not a problem with rsolr. This is the expected behavior when solr doesn't understand your query. In this case Solr is complaining about "undefined field text". I suspect you've got something worn in your solr config.

**Comment by dvohra** [comment]
The only modification made in solrconfig.xml is set following to true.
    <autoCommit> 
       <maxTime>${solr.autoCommit.maxTime:15000}</maxTime> 
       <openSearcher>true</openSearcher> 
     </autoCommit>

And the only modification schema.xml is to add the following fields:
<field name="timestamp" type="string" indexed="true"  stored="true"  multiValued="false" />
<field name="category" type="string" indexed="true"  stored="true"  multiValued="false" />
<field name="type" type="string" indexed="true"  stored="true"  multiValued="false" />
<field name="servername" type="string" indexed="true"  stored="true"  multiValued="false" />
<field name="code" type="string" indexed="true"  stored="true"  multiValued="false" />
<field name="msg" type="string" indexed="true"  stored="true"  multiValued="false" />

**Comment by jcoyne** [comment]
What happens when you run:

curl "http://localhost:8983/solr/wlslog/select?wt=ruby&q=%3A&fq=timestamp&fq=code&fq=msg"

**Comment by dvohra** [comment]
The script which generates the error outputs the following URI in the error message.
URI: http://localhost:8983/solr/wlslog/select?wt=ruby&q=\*%3A\*&fq=timestamp&fq=co
de&fq=msg

**Comment by jcoyne** [comment]
I'm asking you to test if the query you are making with Rsolr works without ruby. I suspect it won't. In which case you've eliminated rsolr as the cause of the problem.

**Comment by dvohra** [comment]
Same error:
curl "http://localhost:8983/solr/wlslog/
select?wt=ruby&q=*%3A*&fq=timestamp&fq=code&fq=msg"
{'responseHeader'=>{'status'=>400,'QTime'=>1,'params'=>{'q'=>'*:*','wt'=>'ruby',
'fq'=>['timestamp','code','msg']}},'error'=>{'msg'=>'undefined field text','code
'=>400}}

**Comment by dvohra** [comment]
And the error is not due to a ',' in a text field. 
"timestamp": "Apr 8, 2014 7:06:16 PM"

Removing the ',' as
"timestamp": "Apr 8 2014 7:06:16 PM"

still generates the same error.

**Comment by dvohra** [comment]
Though not related to rsolr, the error is due to the following default field setting for /query request handler in solrconfig.xml.
<requestHandler name="/query" class="solr.SearchHandler">
     <lst name="defaults">
       <str name="echoParams">explicit</str>
       <str name="wt">json</str>
       <str name="indent">true</str>
       <str name="df">text</str>
     </lst>
  </requestHandler>

  <initParams path="/update/**,/query,/select,/tvrh,/elevate,/spell">
    <lst name="defaults">
      <str name="df">field</str>
    </lst>
  </initParams>

But even if a 'field' field is defined in the schema, the error is removed but no result is listed with a query.
