### ISSUE TITLE
support for atomic updates?

### ISSUE THREAD

**Issue by trampos** [rsolr/rsolr#137]
I tried everything i could to build a RSrol:Xml with an atomic update with no success. if i send one nested hash, it converts the nested hash to string. 

Im running this:

```Ruby
RSolr::Xml::Document.new({ foo: { set: "Bar" } })
```

and the return:

```Ruby
#<RSolr::Xml::Document:0x007f940b61abb0 @fields=[#<RSolr::Xml::Field:0x007f940b61a840 @attrs={:name=>:foo}, @value="{:set=>\"Bar\"}">], @attrs={}>
```

Is there any way to build the correct xml with rsolr?

**Comment by trampos** [comment]
I managed to do that using the update method, changing content type header to json, code:

```Ruby
solr.update(
    :data => [{ foo: { "set" => "bar"} }].to_json,
    :headers => { 'Content-Type' => 'application/json' }
  )
```

**Comment by cbeer** [comment]
Yep, that absolutely works fine. In RSolr 2.0.0.pre1, released earlier today, you should now be able to do:

```
solr.add(id: "id", foo: { set: "bar" })
```
