### ISSUE TITLE
Support for documents with a single child

### ISSUE THREAD

**Issue by hbeachey** [rsolr/rsolr#169]
I just upgraded to 2.0.0-pre1 as I need the support for child documents -- which I'm happy to see being added!

I found that adding a single child causes an error where `_childDocuments_` is not submitted as an array, but just the single document hash which causes solr to return a 400.

**Comment by cbeer** [comment]
Thanks for the bug report. I believe we've addressed the problem in 2.0.0.pre2. Give it a try and let us know.
