### ISSUE TITLE
NameError: uninitialized constant Faraday::FlatParamsEncoder

### ISSUE THREAD

**Issue by ranjithnalimela** [rsolr/rsolr#185]
bundle exec rake sunspot:reindex
NameError: uninitialized constant Faraday::FlatParamsEncoder
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/rsolr-2.0.2/lib/rsolr/client.rb:282:in `connection'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/rsolr-2.0.2/lib/rsolr/client.rb:186:in `execute'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/rsolr-2.0.2/lib/rsolr/client.rb:180:in `send_and_receive'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/sunspot_rails-2.2.7/lib/sunspot/rails/solr_instrumentation.rb:16:in `block in send_and_receive_with_as_instrumentation'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.8/lib/active_support/notifications.rb:123:in `block in instrument'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.8/lib/active_support/notifications.rb:123:in `instrument'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/sunspot_rails-2.2.7/lib/sunspot/rails/solr_instrumentation.rb:15:in `send_and_receive_with_as_instrumentation'
(eval):2:in `post'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/rsolr-2.0.2/lib/rsolr/client.rb:83:in `update'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/rsolr-2.0.2/lib/rsolr/client.rb:146:in `delete_by_query'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/sunspot-2.2.7/lib/sunspot/indexer.rb:68:in `remove_all'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/sunspot-2.2.7/lib/sunspot/session.rb:197:in `block in remove_all'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/sunspot-2.2.7/lib/sunspot/session.rb:197:in `each'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/sunspot-2.2.7/lib/sunspot/session.rb:197:in `remove_all'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/sunspot-2.2.7/lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in `remove_all'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/sunspot-2.2.7/lib/sunspot/session_proxy/retry_5xx_session_proxy.rb:17:in `method_missing'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/sunspot-2.2.7/lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in `remove_all'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/sunspot-2.2.7/lib/sunspot.rb:502:in `remove_all'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/method_tracer.rb:464:in `block in remove_all_with_trace_SolrClient_Sunspot_delete'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/method_tracer.rb:234:in `trace_execution_scoped'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/method_tracer.rb:462:in `remove_all_with_trace_SolrClient_Sunspot_delete'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/sunspot_rails-2.2.7/lib/sunspot/rails/searchable.rb:190:in `solr_remove_all_from_index'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/sunspot_rails-2.2.7/lib/sunspot/rails/searchable.rb:209:in `solr_reindex'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/sunspot_rails-2.2.7/lib/sunspot/rails/tasks.rb:60:in `block (4 levels) in <top (required)>'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/sunspot-2.2.7/lib/sunspot/class_set.rb:16:in `each'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/sunspot-2.2.7/lib/sunspot/class_set.rb:16:in `each'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/sunspot_rails-2.2.7/lib/sunspot/rails/tasks.rb:59:in `block (3 levels) in <top (required)>'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/sunspot_rails-2.2.7/lib/sunspot/rails/tasks.rb:71:in `with_session'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/gems/sunspot_rails-2.2.7/lib/sunspot/rails/tasks.rb:19:in `block (2 levels) in <top (required)>'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/ranjith/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => sunspot:reindex
(See full trace by running task with --trace)

**Comment by jcoyne** [comment]
@ranjithnalimela it looks like you're trying to use ruby 1.9.3.  This version of Ruby reached its end-of-life over 2 years ago and we no longer support it https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/

**Comment by railsfactory-ranjithN** [comment]
@jcoyne Thanks for the response, will try with latest Ruby.
