### ISSUE TITLE
RSolr::Error::Http

### ISSUE THREAD

**Issue by caionakai** [rsolr/rsolr#234]
I'm receiving this error

```

RSolr::Error::Http

URI: http://anythingtest123.com:8983/solr/production/update?wt=json

Request Headers: {"Content-Type"=>"application/json"}

Request Data: "{\"commit\":{\"softCommit\":false}}"


Backtrace: /usr/local/bundle/ruby/2.4.0/gems/rsolr-2.3.0/lib/rsolr/client.rb:206:in `rescue in execute'

/usr/local/bundle/ruby/2.4.0/gems/rsolr-2.3.0/lib/rsolr/client.rb:196:in `execute'

/usr/local/bundle/ruby/2.4.0/gems/rsolr-2.3.0/lib/rsolr/client.rb:191:in `send_and_receive'

/usr/local/bundle/ruby/2.4.0/gems/sunspot_rails-2.5.0/lib/sunspot/rails/solr_instrumentation.rb:16:in `block in send_and_receive_with_as_instrumentation'

/usr/local/bundle/ruby/2.4.0/gems/activesupport-5.2.5/lib/active_support/notifications.rb:168:in `block in instrument'

/usr/local/bundle/ruby/2.4.0/gems/activesupport-5.2.5/lib/active_support/notifications/instrumenter.rb:23:in `instrument'

/usr/local/bundle/ruby/2.4.0/gems/activesupport-5.2.5/lib/active_support/notifications.rb:168:in `instrument'

/usr/local/bundle/ruby/2.4.0/gems/sunspot_rails-2.5.0/lib/sunspot/rails/solr_instrumentation.rb:15:in `send_and_receive_with_as_instrumentation'

(eval):2:in `post'

/usr/local/bundle/ruby/2.4.0/gems/rsolr-2.3.0/lib/rsolr/client.rb:94:in `update'

/usr/local/bundle/ruby/2.4.0/gems/rsolr-2.3.0/lib/rsolr/client.rb:122:in `commit'

```

The error started occurring suddenly, I have a container with Ruby on Rails with the sunspot gem dependency and another one with solr. Any help is appreciated, thanks in advance.

**Comment by jcoyne** [comment]
It looks like it's wrapping an error from faraday: https://github.com/rsolr/rsolr/blob/v2.3.0/lib/rsolr/client.rb#L206

You might want to try upgrading to rsolr 2.5.0 and that can tell you if it's a timeout or something else.  It doesn't look like it got any response or it would be displaying it: https://github.com/rsolr/rsolr/blob/5eee5c552c2975d3ed2fd474ce3ec63f1ed24446/lib/rsolr/error.rb#L11-L15

**Comment by caionakai** [comment]
Hi @jcoyne thanks for answering. Do you know how I can upgrade to rsolr 2.5.0? Because I don't have rsolr as a "direct" dependency, I have the following gems as dependencies and I think sunspot actually has it as a dependency:

```
gem 'sunspot'
gem 'sunspot_rails'
gem 'sunspot_solr'
```

When the error happened I tried to run the `curl -v http://anythingtest123.com:8983/solr` inside the docker container (alpine) I installed the curl using `apk add curl` and the request "worked" or at least I received something as a response. I could also type http://anythingtest123.com:8983/solr in the browser and see the solr's dashboard.

FYI: The containers are in a docker swarm environment I restarted the solr's container, the RoR application's container however I was still getting the error, after some time it was gone I don't know how, that's what worries me (in a production environment 😞 ).

**Comment by jcoyne** [comment]
I think you can do `bundle update rsolr` to get the latest version.

**Comment by jrochkind** [comment]
Yep, `bundle update rsolr`, which should change your Gemfile.lock. `bundle info rsolr` to make sure it gave you the newer version of rsolr. Then commit your new `Gemfile.lock`. 

This error is supposed to mean Solr returned an error message or timed out. That's too bad there isn't more info in the error message about the nature of the Solr error, I believe there is supposed to be, but maybe that's what the rsolr upgrade will give you, hopefully!
