### ISSUE TITLE
Solr URI is not sanitized in RSolr::Error::Http messages 

### ISSUE THREAD

**Issue by esergion** [rsolr/rsolr#235]
If Solr's URI is provided with basic auth credentials (`http://user:password@hostname:8983/solr`) RSolr::Error::Http shows it fully for everyone who can see the exception.

```
RSolr::Error::Http:
RSolr::Error::Http
URI: http://username:REDACTED_PASSWORD@REDACTED-HOSTNAME:8983/solr/admin/update?wt=json
Request Headers: {"Content-Type"=>"application/json"}
Request Data: "{\"commit\":{\"softCommit\":false}}"

Backtrace: /usr/local/bundle/gems/rsolr-2.3.0/lib/rsolr/client.rb:206:in `rescue in execute'
...
```

**Comment by jcoyne** [comment]
@esergion how would you propose something like this is fixed?

It looks like the problem is here: https://github.com/rsolr/rsolr/blob/0f2ce40465818ab547ffc4dd5ea4910bc13a785e/lib/rsolr/error.rb#L16

**Comment by esergion** [comment]
Hey @jcoyne, thanks for the answer!
In this case to achieve some more security I would go with just a hostname, port and path, it should be pretty enough to get info about any network issue.
Unfortunately there's no built in method to clear the uri for printing, so what about just pretty straightforward "patch" with concatenating these uri parts?
Something like this:

```ruby
def clean_uri(uri)
  "#{uri.scheme}://#{uri.user && uri.password ? "REDACTED:REDACTED@" : ''}#{uri.hostname}#{uri.port ? ":#{uri.port}" : ''}#{uri.path}#{uri.query ? "?#{uri.query}" : ''}"
end

uri = URI.parse("http://username:password@hostname.local:8983/solr/admin/update?wt=json&q=test")
clean_uri(uri) # => "http://REDACTED:REDACTED@hostname.local:8983/solr/admin/update?wt=json&q=test"

uri = URI.parse("http://hostname.local:8983/solr/admin/update")
clean_uri(uri) # => "http://hostname.local:8983/solr/admin/update"
```

A bit ugly I know, but currently it pretty seriously compromises Solr credentials for a bunch of people when throws exception into Rollbar for example

**Comment by cgalarza** [comment]
Hello! I am running into this problem. Is there any issue with the approach described by @esergion or is it just a matter of submitting an PR? Thanks!

**Comment by jcoyne** [comment]
I think we just need someone who wants to do that work.

**Comment by cgalarza** [comment]
Great, I'll work on putting together a PR.
