### ISSUE TITLE
Deprecation Messages 

### ISSUE THREAD

**Issue by eclectic-coding** [rsolr/rsolr#242]
There are currently two deprecation warnings, and it looks like one of them will become a breaking change with Rails 7.2:

```shell
DEPRECATION WARNING: BOLD is deprecated! Use MODES[:bold] instead. (called from post at (eval at rsolr-2.6.0/lib/rsolr/client.rb:65):2)
```
And
```shell
DEPRECATION WARNING: Bolding log text with a positional boolean is deprecated and will be removed in Rails 7.2. Use an option hash instead (eg. `color("my text", :red, bold: true)`). (called from post at (eval at rsolr-2.6.0/lib/rsolr/client.rb:65):2)
```

**Comment by jrochkind** [comment]
Thanks for report! Did you see this in your app logs? Hm, can you find any more backtrace to see what called this?   

`lib/rsolr/client.rb:65` is a very abstract kind of method, leaves me unsure what's going on or how to fix it. 

https://github.com/rsolr/rsolr/blob/a60ec42b58f3b068f23537e49d0b6510bb12ee17/lib/rsolr/client.rb#L65-L69

Let's see if I see deprecation warning when running test suite... I don't think I do, although I may not be looking in the right place.  I also don't seem to be able to get my own app to trigger it, don't find it in my app development logs, even though it's using rsolr. 

It's possible this deprecation warning is only triggered based on how a dependent is using rsolr... it could still require a fix in rsolr, I'm just not totally sure what fix and not comfortable trying one without a reproduction I don't have yet!

Looks like it may also be Ruby 3 keywords change related, which would make it even more confusing to fix in a strictly backwards compat way. 

So if I you can figure out the reproduction, or what calling code is triggering this, that would be helpful!

Note also for the record, while I have commit rights on this repo and try to contribute  to keep it working (and it is a dependency in some of my apps), as far as I know it is not getting a lot of maintainance attention, and I personally don't necessarily recommend it for new projects!

**Comment by eclectic-coding** [comment]
@jrochkind I will see if I can get some more stack trace

For context, the deprecation warning started with the latest upgrade to Ruby 3.3.3/Rails 7.1. I assumed, these messages are pushed by Rails, in anticipation of the Rails 7.2 release later this year.

I will be in touch

**Comment by jrochkind** [comment]
Thanks! I think you are right the deprecation message is coming from Rails 7.1.  But I am not currently able to reproduce it in Rsolr tests or my own Rsolr install, even with Rails 7.1, those don't seem to be triggering the deprecation message.

**Comment by eclectic-coding** [comment]
I can confirm that we can close this issue.
When upgrading to Rails 7.2 the message disappears, and all my tests pass in the application. Rsolr seems to be working as expected.
