### ISSUE TITLE
deprecation warning question

### ISSUE THREAD

**Issue by jrochkind** [rsolr/rsolr#33]
When I run Blacklight's own tests, I get this deprecation warning output to stdout/stderr:

     DEPRECATION WARNING: RSolr::Pagination / pagination functionality will be removed in 1.1.0.

It's not clear to me exactly what line in Blacklight is causing this output. As far as I know, Blacklight is not in fact using any "RSolr::Pagination / pagination functionality". But perhaps it is accidentally?

Can you give me any hints as to what usage will cause this message to be output, or what line in RSolr code outputs this so I can try to reverse engineer it myself?  I'd like to fix Blacklight's calling of RSolr so it will not result in this deprecation warning.

**Comment by ndushay** [comment]
I believe this is no longer an issue.
