### ISSUE TITLE
Non-blocking API?

### ISSUE THREAD

**Issue by bachue** [rsolr/rsolr#67]
Hi,
Does RSolr support non-blocking API?
I read some of code in it and I found it uses net/http. There's no non-blocking API in it, right? So I can't send multiple requests to Solr parallel.
Would you mind to add this feature? You could use Faraday to make this work easier.
Thanks!

**Comment by cbeer** [comment]
We've switched to Faraday in RSolr 2.0, and it should be possible to configure the adapter to use a non-blocking client.
