### ISSUE TITLE
'update'

### ISSUE THREAD

**Issue by nathantechie9** [rsolr/rsolr#68]
line 67 of client.rb

'update' isn't a full path enough for it to know where to post the data to for adding new documents.

I had to hard code my path like so...
post 'http://localhost:8982/solr/update/', opts

**Comment by ndushay** [comment]
Were you using  #update method  as in h ttps://github.com/rsolr/rsolr/blob/master/lib/rsolr/client.rb#L79?  Can you provide a snippet of the code using the RSolr::Client class so we have more context?  Thanks.

**Comment by nathantechie9** [comment]
I never ran into this problem again. I think it's fixed.
