### ISSUE TITLE
Not possible to bypass http_proxy environment variable when using ruby 2.0

### ISSUE THREAD

**Issue by jhsveli** [rsolr/rsolr#70]
In Ruby 2.0+, you are required to explicitly pass nil for proxy address when initializing Net::HTTP.
(http://ruby-doc.org/stdlib-2.0.0/libdoc/net/http/rdoc/Net/HTTP.html#method-c-new)

When passing proxy = nil to Rsolr.connect, http is initalized with proxy read from ENV:

```
Net::HTTP.new uri.host, uri.port
```

This behaviour differs in 2.0 from 1.9.3 and eariler, where Rsolr would connect without proxy.

This is a problem for us since we must use the proxy configured in env for other requests, but can't use it for communicating with solr

**Comment by ndushay** [comment]
Does this relate to #62 ?   How about

**Comment by cbeer** [comment]
Fixed by #124
